# User config
author: "SJ Media"
tagline: ""
description: "We to my portfolio. I am a graphic designer and photographer, with a focus on documentary and vector work."
keywords: "SJ, SJ Media, graphics, design, photography"
email: ""
linkedin: ""
twitter: ""
github: ""

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
